// Claves centralizadas de React Query (evita strings mágicos y typos).
export const qk = {
  profile: ['profile'] as const,
  courses: ['courses'] as const,
  schedule: ['schedule'] as const,
  evaluations: ['evaluations'] as const,
  tasks: ['tasks'] as const,
  habits: ['habits'] as const,
  habitLogs: ['habit_logs'] as const,
  notifications: ['notifications'] as const,
  transactions: ['transactions'] as const,
  transfers: ['transfers'] as const,
  accounts: ['accounts'] as const,
  budgets: ['budgets'] as const,
  savingsGoals: ['savings_goals'] as const,
  savingsRules: ['savings_rules'] as const,
  focusSessions: ['focus_sessions'] as const,
  rewards: ['rewards'] as const,
  lifeGoals: ['life_goals'] as const,
  weeklyReview: (weekStart: string) => ['weekly_review', weekStart] as const,
}
